### PR TITLE
Version 0.5 

### LINKED ISSUE #57: Add Tag Icon
Ability To Add Icon to a Tag

### PR DESCRIPTION
**Pull request by rmountjoy92**
**Changelog**
- ui fixes
- users are now managed through config.ini
- no more alembic, completely dynamic database, created on startup
- users can now override global settings
- added update message
- performance fixes
- added setting for hiding sidebar by default
- broke up config readme into 3 tabs, and 3 .md files
- changed 'app templates' to 'card templates'
- added 'collection' cards
- added 'custom' cards
- added options for setting tag icons and sort position
- removed list view to focus on different card types on /home
- added ability to collapse/expand tags on /home
- added setting for having tags default to collapsed state
- created a public user view with no sidebar
- added sidebar default overrides for users
- fixes #57, #55, #45, #41, #40

### CODE REVIEW

**Comment by arejaytee** [comment]
Was not able to log in after this, just always greeted with unauthorised.

**Comment by rmountjoy92** [comment]
Go to /login and use admin and admin. You will see an explanation.

**Comment by arejaytee** [comment]
Had to delete my old installation before /login will load ¯\_(ツ)_/¯

**Comment by rmountjoy92** [comment]
Weird,  I tested the update with as many scenarios as I could think of to make the update smooth, guess I missed something. Sorry about that. Updates should be a lot smoother moving forward.

**Comment by LostSoulfly** [comment]
> * added sidebar default overrides for users

I don't seem to be able to re-enable the sidebar for the public user. How do I go about doing this?

**Pull request merged**
