### PR TITLE
Add Plex as a platform

### PR DESCRIPTION
**Pull request by reedhaffner**
[X] I'm submitting a platform
- [X] I looked at the other platform examples and followed a very similar methodology.
- [X] I added a docstring at the top of my platform file that is formatted exactly like rest.py
- [x] I added sample code to any template app that this platform works for, look at deluge.ini in /template_apps/ for an example
- [X] I have thoroughly tested this platform and it works
- [X] I am committed to updating this platform if something breaks it in the future

### CODE REVIEW

**Comment by rmountjoy92** [comment]
Hey! sorry for the late reply. Just wanted to let you know that merging pull request in v0.6 is high on my list of priorities. It's not an easy as usual, because there are a lot of major back end changes in v0.6, so I will need to edit all PR's to be compatible with the new version. I will close this PR once this is added to 0.6 :)

**Comment by rmountjoy92** [comment]
Hey @reedhaffner ! So sorry for how long this has taken. I've been struggling to find free time during this virus situation. I just added these 0.5 and modified them to work with 0.6, do you mind spinning up v0.6 and making sure everything is still working okay? Thank you so much for your contributions, I'm stoked to personally start using these.

**Comment by reedhaffner** [comment]
I’ll review it on Tuesday when I get back home 👍 hopefully it doesn’t interfere with with 0.6 release

**Comment by reedhaffner** [comment]
I spun up 0.6 and it works perfectly.

**Pull request closed without merging**
